apiVersion: v1
kind: Service
metadata:
  name: taxicab-ENVIRONMENT-svc-BUILD_NUMBER
  namespace: default
spec:
  type: NodePort
  ports:
    - nodePort: 30080
      port: 80
      targetPort: 8080
      name: http
    - name: "https"
      nodePort: 30443
      port: 443
      targetPort: 8080
      protocol: "TCP"
  selector:
    app: taxicab
    version: "BUILD_NUMBER"
