apiVersion: v1
kind: Service
metadata:
  name: taxicab-ENVIRONMENT-svc-BUILD_NUMBER
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - name: "https"
      port: 443
      targetPort: 8080
      protocol: "TCP"
  selector:
    app: taxicab
    version: "BUILD_NUMBER"
